package com.shop.shop.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
public class Member {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long sequence;
    private String memberId;
    private String password;
    @Column(name = "name", length = 10)
    private String name;
    @NotNull
    private Date birth;
    private Membership membership;
}


/*
*
*
drop table if exists member CASCADE;
create table member
(
 sequence bigint generated by default as identity,
 member_id varchar(10),
 password varchar(10),
 name varchar(10),
 birth datetime,
 primary key (sequence),
 constraint uq1 unique (member_id)
 );
*
* */